# /// script
# dependencies = ["jinja2"]
# ///

# Author: Salvatore Santoro <sal.santoro@studenti.unina.it>
# Author: Vincenzo Maisto <vincenzo.maisto2@unina.it>
# Description: Parse PBUS config and generate HAL header

import csv
import sys
import os
from jinja2 import Template

# Check for correct number of arguments
if len(sys.argv) != 3:
    print("Usage: '<CONFIG_PERIPHERALS_CSV>' <OUTPUT_HAL_CONF_FILE>")
    sys.exit(1)

peripheral_csv_path = sys.argv[1]
output_hal_conf_file = sys.argv[2]

if peripheral_csv_path is None:
    print("[ERROR]: config_peripheral_bus.csv not found")
    sys.exit(1)

# List of device peripherals, needs to be a set to avoid duplicates
devices = set()

# Open the file whose path is stored in peripheral_csv_path
with open(peripheral_csv_path, "r") as file:
    reader = csv.reader(file)
    # For each line
    for property, value in reader:
        if property == "RANGE_NAMES":
            names = value.split(" ")
            for name in names:
                if name.startswith("TIM"):
                    devices.add("TIM")
                else:
                    devices.add(name)
            break

# Convert the set in a list
devices = list(devices)
# Extract base name and make it a valid macro name for the include guard
base_filename = os.path.basename(output_hal_conf_file).replace(".", "_").upper()
include_guard = f"__{base_filename}__"

hal_template_str = r"""/* File generated by {{ current_file_path }}*/
#ifndef {{ include_guard }}
#define {{ include_guard }}

{% for device in devices -%}
#define {{ device.upper() }}_IS_ENABLED 1
{% endfor %}
#endif // {{ include_guard }}
"""

template = Template(hal_template_str)

rendered = template.render(
    current_file_path=os.path.basename(__file__),
    include_guard=include_guard,
    devices=devices,
)
# === Output to file ===
with open(output_hal_conf_file, "w") as f:
    f.write(rendered)
