# Author: Salvatore Santoro <sal.santoro@studenti.unina.it>
# Author: Vincenzo Maisto <vincenzo.maisto2@unina.it>
# Description: Parse PBUS config and generate HAL header

import csv
import sys
import os

# Check for correct number of arguments
if len(sys.argv) != 5:
    print("Usage: <CONFIG_PERIPHERALS_CSV> <CONFIG_MAIN_BUS_CSV> <CONFIG_HIGH_PERFORMANCE_BUS_CSV> <OUTPUT_HAL_CONF_FILE>")
    sys.exit(1)

config_file_names = sys.argv[1 : -1]
output_hal_conf_file = sys.argv[-1]

range_names = []
range_base_addr = []
range_addr_width = []
# List of device peripherals, needs to be a set to avoid duplicates
devices = set()

for fname in config_file_names:
    # Open the configuration files and parse them as csv
    with open(fname, "r") as file:
        reader = csv.reader(file)

        # next gets a single value
        protocol = next(value for property, value in reader if property == "PROTOCOL")
        if protocol == "DISABLE":
            continue

        # read the rows we need
        names = next(value.split(" ") for property, value in reader if property == "RANGE_NAMES")
        base_addr = next(value.split(" ") for property, value in reader if property == "RANGE_BASE_ADDR")
        addr_width = next(value.split(" ") for property, value in reader if property == "RANGE_ADDR_WIDTH")

        # take peripherals and add them to the devices set
        if "peripheral" in fname:
            for name in names:
                # Use a generic TIM to enable timer driver
                if name.startswith("TIM"):
                    devices.add("TIM")
                else:
                    devices.add(name)

        # add the "Value" property to the correnspoding list
        range_names += names
        range_base_addr += base_addr
        range_addr_width += addr_width


# build the peripheral list
peripherals = []
for name, addr, width in zip(range_names, range_base_addr, range_addr_width):
    # not a peripheral
    if name.endswith("BUS"):
        continue

    peripherals.append({
        "device": name,
        "base": int(addr, 16),
        "range": int(width)
    })

# Convert the set in a list
devices = list(devices)
# Extract base name and make it a valid macro name for the include guard
base_filename = os.path.basename(output_hal_conf_file).replace(".", "_").upper()
include_guard = f"__{base_filename}__"

hal_template_str = r"""/* File generated by {current_file_path} */

#ifndef {include_guard}
#define {include_guard}

#include <stdint.h>

{peripheral_block}

{device_block}

#endif // {include_guard}
"""

def render_devices(devices: list) -> str:
    lines = []
    for d in devices:
        lines.append(f"#define {d.upper()}_IS_ENABLED 1")
    return "\n".join(lines)


def render_peripherals(peripherals: list) -> str:
    lines = []
    for p in peripherals:
        name = p["device"]
        base = p["base"]
        size = p["range"]
        lines.append(f"#define _peripheral_{name}_start  0x{base:016x}")
        lines.append(f"#define _peripheral_{name}_end    0x{base + (1 << size):016x}")
    return "\n".join(lines)


if __name__ == "__main__":

    rendered = hal_template_str.format(
        current_file_path=os.path.basename(__file__),
        peripheral_block=render_peripherals(peripherals),
        include_guard=include_guard,
        device_block=render_devices(devices),
    )

    # === Output to file ===
    with open(output_hal_conf_file, "w") as f:
        f.write(rendered)
