#ifndef UNINASOC_H
#define UNINASOC_H

#include "stdlib.h"
#include "tinyIO.h"
#include "io.h"

// This header is autogenerated based on project configuration
#include "uninasoc_conf.h"

#include "irq_handlers.h"
#include "plic.h"

#ifdef GPIO_IN_IS_ENABLED
#include "xlnx_gpio_in.h"
#endif

#ifdef GPIO_OUT_IS_ENABLED
#include "xlnx_gpio_out.h"
#endif

#ifdef TIM_IS_ENABLED
#include "xlnx_tim.h"
#endif

enum{
    UNINASOC_OK,
    UNINASOC_ERROR
};


/* Initialize UninaSoC HAL */
void uninasoc_init(void);

#endif // UNINASOC_H
